# Generated by Django 3.2.7 on 2021-09-16 06:37

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0002_auto_20210916_0620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='cast',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, size=None),
        ),
    ]
