# Generated by Django 3.2.7 on 2021-09-28 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IMDB', '0007_alter_rating_unique_together'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='thumbnail',
            new_name='poster',
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
